### ISSUE TITLE
config system and a question

### ISSUE THREAD

**Issue by reaperpaster** [lagcomp/wok-csgo-sdk-v2#16]
1. I saw the issue #6 but I still don't know how to do it works for color picker since colorpicker needs float[4] and I can't use float[4] in ADD_ITEM for example: ADD_ITEM(float[4] "m_example_color", { 255, 255, 255, 255 });
It doesn't work, i could try to use col_t instead of float but ImGui::ColorEdit4 only accepts float[4] as argument, so how I can do it?
2. Why menu closes when I have it opened and I minimize the game, not an issue but a question

**Comment by reaperpaster** [comment]
I solved the first issue.

**Comment by st3ph4nnn** [comment]
are you retarded? did u even check how the config system load and save works? float[4] doesnt exists. just use normal float, it will work fine. like this: `ADD_ITEM(float "m_example_color", (255, 255, 255, 255));`

**Comment by lagcomp** [comment]
personally i not using imgui
but u can create a wrapper for std::array<float, 4> and then use it
