### ISSUE TITLE
config system doesnt work?

### ISSUE THREAD

**Issue by st3ph4nnn** [lagcomp/wok-csgo-sdk-v2#17]
so i wanted to make a little bhop thing and i did, i added a item bool which is false in the config init, i checked if that bool is true in my bhop code, and then if i make a checkbox and enable it, it will work, but the thing is it will work the same as if the checkbox wasnt checked. i also tried with some dme chams, still the same isssue, its like the  config items were never there and everything its enabled. this only occurs for the bools, rest of the stuff works fine.

This is what i do in cfg::init
`void init() {
		ADD_ITEM(bool, "bunny", false);
}`

then in my bunnyhop code 

`void c_movement::bunnyhop(c_user_cmd* cmd) {
	if (&cfg::get<bool>(FNV1A("bunny"))) {
		(the bunnyhop code)
	}
}`

but yet it does it everytime

**Comment by lagcomp** [comment]
u need to remove "address of" `&` operator....
