### ISSUE TITLE
sidemove forwardmove upmove

### ISSUE THREAD

**Issue by rat1nov** [lagcomp/wok-csgo-sdk-v2#3]
i check source and find only m_move with x, y, z.
So, sidemove = y forwardmove = y upmove = z, i`m correct?

**Comment by lagcomp** [comment]
size of vec3_t - 12 bytes(3 floats), forward/side/up - 3 floats which size are 12 bytes too
first will be x when y and z
in valve's cmd struct they goes like forward/side/up
so forward will be x | side - y | up - z
using vectors for move in my opinion looks better than just floats
