### ISSUE TITLE
ADD_ITEM_BOOL_VEC

### ISSUE THREAD

**Issue by barthomermarge** [lagcomp/wok-csgo-sdk-v2#31]
How do i use this with imgui?

I can't find anything that converts it into a bool*   (like the ADD_ITEM_FLOAT_VECs "data()" does).

**Comment by lagcomp** [comment]
https://en.cppreference.com/w/cpp/container/vector/data 🤔
if ur function takes as argument ptr to object (not array) u can do it like i mentioned here #6
