### ISSUE TITLE
chams

### ISSUE THREAD

**Issue by sadboy9x** [lagcomp/wok-csgo-sdk-v2#39]
I can't do hand chams, probably a problem with the hook

**Comment by sowwe** [comment]
![image](https://user-images.githubusercontent.com/13748681/96369502-02b84f80-1163-11eb-9637-d683c6e8d0c7.png)

**Comment by sadboy9x** [comment]
`		const auto entity = reinterpret_cast<c_base_entity*>(interfaces::entity_list->get_client_entity(info.m_index));
	if (!entity)
		return true;

	if (entity->is_player())
	{
		const auto player = reinterpret_cast<c_cs_player*>(entity);
		if (!player->is_alive()
			|| !player->is_enemy())
			return true;

		override_material(MATERIAL_TYPE_REGULAR, col_t::palette_t::purple(), true);

		original(ecx, context, state, info, bones);

		return override_material(MATERIAL_TYPE_REGULAR, col_t::palette_t::purple(), false);
	}
	else if (strstr("arms", info.m_model->m_name))
	{
		return override_material(MATERIAL_TYPE_REGULAR, col_t::palette_t::purple(), false);
	}
	return true;`
Also, the chams don't work if I remove the checks (player and arms) and override material in all entities, mostly doesn't work, like hands, weapons in ground, etc, I tested and looks like there is a better way to get the current drawmodel hook entity

**Comment by sowwe** [comment]
strstr(info.m_model->m_name, "arms")
http://www.cplusplus.com/reference/cstring/strstr/

also comparing strings to filter model isn't good idea.

```
bool c_chams::on_draw_model(i_model_render* ecx, void* context, const draw_model_state_t& state, const model_render_info_t& info, matrix3x4_t* bones) {
	if (strstr(info.m_model->m_name, "arms"))
		override_material(MATERIAL_TYPE_REGULAR, col_t::palette_t::purple(), false);

	return true;
}
```

![image](https://user-images.githubusercontent.com/13748681/96375528-2f2f9400-1182-11eb-9c4f-50e1cb8b20e4.png)

**Comment by sadboy9x** [comment]
oh thank you! one more thing, is there some way to convert the float vector to col_t to use the color in chams?

**Comment by sowwe** [comment]
https://github.com/lagcomp/wok-csgo-sdk-v2/commit/bc6ee989483eca71106de43008a0997135ec3dbf

**Comment by sadboy9x** [comment]
I mean, how to convert the float that is used in colorpicker example::clr3 to a col_t to be used in chams etc

**Comment by sadboy9x** [comment]
everything is working now, thank you for helping me.
