### ISSUE TITLE
movement fixer

### ISSUE THREAD

**Issue by rat1nov** [lagcomp/wok-csgo-sdk-v2#4]
I try to add a movement fixer with bhop, and all fixers breack movement in game. I try use other clear csgo base and it work fine, but not in yours, i dont hane any idea why its happened, maybe u can help?

**Comment by lagcomp** [comment]
im fixing my movement like [this](https://pastebin.com/PFjEayRr)
first argument will be unmodified view angles which i getting at the start of create_move 
and second will be cmd's view angles which i normalizing using function in qangle_t struct before this
and everyting working fine
so problem must be with ur code

**Comment by lagcomp** [comment]
dc9f757b63ec5b15d941a963d9776596042234ce

**Comment by sowwe** [comment]
Кто придумал этот мувмент фиксер, у меня на лестнице с аа пидорасит, и в ноклипе в сторону хуярит 🥺🥺🥺

**Comment by lnk1181** [comment]
все туда работает проблемы в твоем коде 😡 😡 😡
