### ISSUE TITLE
hook problems

### ISSUE THREAD

**Issue by sadboy9x** [lagcomp/wok-csgo-sdk-v2#43]
1. If you inject mid-game player hooks (setupbones, geteyeangles) don't work, but they work normally if you inject before joining a game.
2. If you unload the cheat mid-game the game crashes, but unload normally without crashes if you disconnect and then unload

**Comment by sadboy9x** [comment]
I hope this gets fixed soon

**Comment by lagcomp** [comment]
https://github.com/lagcomp/wok-csgo-sdk-v2/discussions/82
