### ISSUE TITLE
config system

### ISSUE THREAD

**Issue by glidinglikeafly** [lagcomp/wok-csgo-sdk-v2#6]
How do you use configuration system to communicate with the menu(ImGui)?

**Comment by lagcomp** [comment]
0___o
`cfg::get<type>(hash)`

**Comment by glidinglikeafly** [comment]
Do you mean like this?

// cfg.cpp file
`void init() {
		ADD_ITEM(bool, "m_bhop", false)
	}`

// menu.cpp
`
ImGui::Checkbox("Bunny Hop", cfg::get<bool>("m_bhop"));
`

**Comment by lagcomp** [comment]
`ImGui::Checkbox("Bunny Hop", &cfg::get<bool>(fnv1a("m_bhop")));`
