### ISSUE TITLE
detour hooking?

### ISSUE THREAD

**Issue by glidinglikeafly** [lagcomp/wok-csgo-sdk-v2#69]
title...

**Comment by sowwe** [comment]
@lagcomp реально а где детуры и вок-гуи

**Comment by ZeroXKiritsu** [comment]
> @lagcomp реально а где детуры и вок-гуи

там же где он и сам

**Comment by sowwe** [comment]
in progress

**Comment by lagcomp** [comment]
https://github.com/lagcomp/wok-csgo-sdk-v2/discussions/82
